protected/controllers/SiteController.php
<?php

/**
 * Class SiteController
 *
 * Default website controller
 */
class SiteController extends Controller {

    public $obeder; 
    public $title = '';
    
    public function filters() {
        return array(
            'accessControl',
        );
    }

    public function accessRules() {
        return array(
            array('allow',
                'actions' => ['index', 'login'],
                'users' => array('?'),
            ),
            array('deny',
                'actions' => array('buy', 'unbuy', 'order', 'download', 'removeorder'),
                'users' => ['?'],
            ),
            array('deny',
                'actions' => array('delete'),
                'users' => array('*'),
            ),
        );
    }
    
    public function actionRegister(){
        $error = '';
        if(!empty($_POST)){
            
            
            $email = empty($_POST['username'])? '' : $_POST['username'];
            $pass = empty($_POST['password'])? '' : $_POST['password'];
            $nickname = empty($_POST['name'])? '' : $_POST['name'];
            $user = User::model()->findAllByAttributes(['mail'=>$email]);
            if(!empty($user)){
                $error = 1;
            }
            else{
                
                Controller::xmail($email, 
                    'Добро пожаловать в Obeder!', 
                    '<h1>Привет '.$nickname.'!</h1><p>Ты успешно зарегистрирован!</p>'
                    . '<p>Логин: '.$email.' Пароль: '.$pass.'</p>');
                
                $user = new User();
                $user->pswd = md5($pass);
                $user->mail = $email;
                $user->nickname = $nickname;
                $user->subscribe = 1;
                
                if($user->save()){
                    Yii::app()->runController('site/login');
                    return true;
                }
            }
            
        }
        
        $this->render('register', ['error'=>$error]);
    }

    /**
     * default action
     */
    public function init() {
        parent::init();
        $this->obeder = new Obeder();
        $this->obeder->checkMenu();
    }
    
    

    public function actionRecovery() {
        $error = 0;
        $sended = false;
        if(!empty($_POST['username'])){
            $mail = $_POST['username'];
            $user = User::model()->findByAttributes(['mail'=>$mail]);
            if(!empty($user)){
                $pswd = mt_rand(100000, 999999);
                $user->pswd = md5($pswd);                
                if($user->save()){
                    Controller::xmail($mail, 'Восстановление пароля', '<h1>Ваше новый пароль: '.$pswd.'</h1>');
                    $sended = true;
                }
            }else{
                $error = 1;
            }
        }
        
        
        $this->render('recovery', ['sended'=>$sended, 'error'=>$error]);
    }

    public function actionLogin() {
        $error = null;
        if ($_POST) {
            $identity = new UserID($_POST['username'], $_POST['password']);
            if ($identity->authenticate()) {
                Yii::app()->user->login($identity, 3600 * 24 * 31);
                $this->redirect(['site/index']);
            } else {
                $error = $identity->errorCode;
            }
        }

        $this->render('login', ['error' => $error]);
    }

    public function actionLogout() {
        if (!Yii::app()->user->isGuest)
            Yii::app()->user->logout();
        $this->redirect(['site/index']);
    }

    public function actionIndex($dayofweek = false) {
        if ($dayofweek == false) {
            $dayofweek = date('w') + 1;
            while (true) {
                $menu = $this->obeder->generateMenuToday($dayofweek);
                if ($menu != false || $dayofweek > 10) break;
                $dayofweek++;
            }

        } else {
            $menu = $this->obeder->generateMenuToday($dayofweek);
        }

        
        $result = false;
        //Если меню есть, тогда дергаем категории
        if ($menu != false) {
            $category = Category::model()->findAll();
            $result = [];
            foreach ($category as $cur) {
                $saveName = false;
                foreach ($menu as $m) {
                    if ($m['category'] == $cur->id) {
                        $result[$cur->id]['products'][] = $m;
                        $saveName = true;
                    }
                }
                if ($saveName) {
                    $result[$cur->id]['name'] = $cur->name;
                }
            }
        }

        $date = strtotime(Obeder::dowToDate($dayofweek));

        $this->render('index', [
            'menu' => $result,
            'dayofweek' => $dayofweek,
            'date' => $date,
        ]);
    }

    public function actionError($error = '') {
        $this->render('error', ['error' => !empty($error) ? $error : Yii::app()->errorHandler->error]);
    }

    public function actionUnbuy($id, $date, $dayofweek) {
        return $this->actionBuy($id, $date, $dayofweek, false);
    }

    public function actionBuy($id, $date, $dayofweek, $plusOne = true) {

        $order = new Order();
        $user_id = Yii::app()->user->id;
        $date = date('Y-m-d H:i:s', $date);
        
        $result = $order->find('product_id=:product_id AND user_id=:user_id AND date = CAST(:date AS DATE)', [
            ':date' => $date,
            ':user_id' => $user_id,
            ':product_id' => $id,
        ]);

        //var_dump($result);die;

        if (!empty($result)) {
            
            if ($plusOne == false) {
                if ($result->count < 2) {
                    $result->delete();
                } else {
                    $result->count--;
                }
            } else {
                $result->count++;
            }
            if (!$result->save()) {
                print_r($result->errors);
            }
        } else {
            $order->user_id = $user_id;
            $order->date = $date;
            $order->count = 1;
            $order->product_id = $id;

            if (!$order->save()) {
                
                print_r($order->errors);
            }
        }
        $this->redirect(['site/index', 'dayofweek'=>$dayofweek]);
    }

    public function actionStat() {
        return new Stat();
    }
    
    public function actionRemoveOrder($date, $id){
        if(!$this->isAdmin()) 
            return false;
        $order = Order::model()->findByPk($id);
        if(!empty($order)){
            if($order->delete()){
                $this->redirect(
                    [
                        'site/order', 
                        'date'=>date('d.m.Y', $date),
                    ]);
            }
        }
    }
    
    public function actionDownload(){
        $time = intval($_POST['download']);
        $date = date('Y-m-d H:i:s', $time);
        $order = Obeder::getAgregateOrder($date);
        Obeder::generateXL($order, $date);
    }

    public function actionOrder($date = null) {
        

        Yii::app()->clientScript->registerCssFile(Yii::app()->getBaseUrl() . '/css/datepicker.css');
        Yii::app()->clientScript->registerCssFile(Yii::app()->getBaseUrl() . '/css/jquery-ui.min.css');
        Yii::app()->clientScript->registerCssFile(Yii::app()->getBaseUrl() . '/css/jquery-ui.structure.min.css');
        Yii::app()->clientScript->registerCssFile(Yii::app()->getBaseUrl() . '/css/jquery-ui.theme.min.css');
        Yii::app()->clientScript->registerCss('order', '.admin-remove{display: none}', 'print');

        if ($date == null) {
            $date = Obeder::getDateByNextOrder();
            
        } else {
            $date = explode('.', $date);
            $date = date('Y-m-d H:i:s', strtotime($date[2] . '-' . $date[1] . '-' . $date[0]));
        }

        $users = Yii::app()->db->createCommand()->selectDistinct('m.user_id, u.nickname as name')
                ->from('order m')
                ->leftJoin('users u', 'u.id = m.user_id')
                ->where('date = CAST(:date AS DATE)', [
                    ':date' => $date
                ])->queryAll();

        $date = strtotime($date);

        if (!empty($users)) {

            $orders = [
                'sum' => 0,
                'users' => [],
            ];

            foreach ($users as $u) {
                $order = Obeder::getOrderByUser($u['user_id'], $date);
                if (!empty($order)) {
                    $orders['users'][$u['user_id']]['name'] = !empty($u['name']) ? $u['name'] : 'unknown';
                    $sum = 0;
                    foreach ($order as $o) {
                        $sum += $o['total'];
                    }
                    $orders['sum'] += $sum;
                    $orders['users'][$u['user_id']]['sum'] = $sum;
                    $orders['users'][$u['user_id']]['products'] = $order;
                }
            }
            if (!empty($orders['users'])) {
                if ($orders['sum'] <= 1000)
                    $orders['delivery'] = 200;
                elseif ($orders['sum'] > 1000 && $orders['sum'] <= 1500)
                    $orders['delivery'] = 100;
                elseif ($orders['sum'] > 1500)
                    $orders['delivery'] = 0;

                $orders['total'] = $orders['sum'] + $orders['delivery'];

                $deliverPersone = round($orders['delivery'] / sizeof($orders['users']));

                foreach ($orders['users'] as &$user) {
                    $user['total'] = $deliverPersone + $user['sum'];
                }
            } else {

protected/views/site/_user_menu.php
<?php if ($menu == false): ?>
    <h3 class="bg-warning">Меню на <?php echo date('d.m.Y', $date); ?> еще не сформированно</h3>
<?php else: ?>
    <?php foreach ($menu as $category): ?>
        <h3><?php echo $category['name'] ?></h3>
        <table class="table">
            <colgroup>
                <col width="5%"/>
                <col width="65%"/>
                <col width="10%"/>
                <col width="10%"/>                
                <col width="10%"/>
            </colgroup>
            <tr>
                <th style="border-top:none;">#</th>
                <th style="border-top:none;">Наименование</th>
                <th style="border-top:none;">Вес</th>
                <th style="border-top:none;">Цена</th>       
                <th style="border-top:none;">Заказ</th>

            </tr>
            <?php $i = 0; ?>
            <?php foreach ($category['products'] as $row): ?>
            
                <tr>
                    <td><?php echo ++$i ?></td>
                    <td><?= $row['name'] ?></td>
                    <td><?= $row['weight'] ?></td>
                    <td><?= $row['price'] ?></td>            

                    <td>
                        <?php if (empty($row['count'])): ?>                
                            <span class="btn btn-default"><i class="glyphicon glyphicon-minus"></i></span>
                            <b>0</b>
                        <?php else: ?>
                            <?php echo CHtml::link('<i class="glyphicon glyphicon-minus"></i>', ['site/unbuy', 'id' => $row['id'], 'date' => $date,'dayofweek'=>$dayofweek], ['class' => 'btn btn-danger']); ?>
                            <b><?= $row['count']; ?></b>
                        <?php endif; ?>


                        <?= CHtml::link('<i class="glyphicon glyphicon-plus"></i>', ['site/buy', 'id' => $row['id'], 'date' => $date, 'dayofweek'=>$dayofweek], ['class' => 'btn btn-success']); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php endforeach; ?>
<?php endif; ?>

<script>
    $(function(){
        $(document).on('click', '.table a.btn', function(){
            var t = $(this),
                minusBtn = t.parents('td').eq(0).children().eq(0),
                cntWrap = t.siblings('b'),
                newCnt = (t.hasClass('btn-success')) ? +cntWrap.text() + 1 : (cntWrap.text() == '0') ? '0' : +cntWrap.text() - 1,
                id, date, dayofweek, href, tmp;
            $.ajax(t.attr('href'));
            cntWrap.text(newCnt);
            if (newCnt > 0) {
                href = t.parents('td').eq(0).children(':last').attr('href');
                tmp = href.substr(href.indexOf('id=') + 3);
                id = tmp.substring(0, tmp.indexOf('&'));
                tmp = href.substr(href.indexOf('date=') + 5);
                date = tmp.substring(0, tmp.indexOf('&'));
                dayofweek = href.substr(href.indexOf('dayofweek=') + 10);
                minusBtn.replaceWith('<a class="btn btn-danger" href="/index.php?r=site/unbuy&id=' + id + '&date=' + date + '&dayofweek=' + dayofweek + '"><i class="glyphicon glyphicon-minus"></i></a>');
            } else {
                minusBtn.replaceWith('<span class="btn btn-default"><i class="glyphicon glyphicon-minus"></i></span>');
            }
            return false;
        });
    });
</script>

protected/views/site/error.php
<h1>Ой! Всё</h1>
<p class="text-danger">Произошла какая то ошибка</p>
<div class="bg-danger">
    <p class="text-danger"><?php echo( $error['message']) ?></p>
</div>

protected/views/site/index.php
<?php $this->title = ' - Меню на '.Obeder::currentDate($date); ?>

<h3>Меню на <?php echo Obeder::currentDate($date)?> <small><?php echo date('d.m.y', $date)?></small></h3>
<div>


    <?php
    $this->widget('zii.widgets.CMenu', array(
        'items' => array(
            array('active' => $dayofweek == 1, 'label' => 'Понедельник', 'url' => array('site/index', 'dayofweek' => 1)),
            array('active' => $dayofweek == 2, 'label' => 'Вторник', 'url' => array('site/index', 'dayofweek' => 2)),
            array('active' => $dayofweek == 3, 'label' => 'Среда', 'url' => array('site/index', 'dayofweek' => 3)),
            array('active' => $dayofweek == 4, 'label' => 'Четверг', 'url' => array('site/index', 'dayofweek' => 4)),
            array('active' => $dayofweek == 5, 'label' => 'Пятница', 'url' => array('site/index', 'dayofweek' => 5)),
            array(
                'label' => 'Следующая неделя <span class="caret"></span>',
                'url' => '#',
                'encodeLabel' => false,
                'items' => array(
                    array('active' => $dayofweek == 6, 'label' => 'Понедельник', 'url' => array('site/index', 'dayofweek' => 6)),
                    array('active' => $dayofweek == 7, 'label' => 'Вторник', 'url' => array('site/index', 'dayofweek' => 7)),
                    array('active' => $dayofweek == 8, 'label' => 'Среда', 'url' => array('site/index', 'dayofweek' => 8)),
                    array('active' => $dayofweek == 9, 'label' => 'Четверг', 'url' => array('site/index', 'dayofweek' => 9)),
                    array('active' => $dayofweek == 10, 'label' => 'Пятница', 'url' => array('site/index', 'dayofweek' => 10)),
                ),
                'linkOptions' => [
                    'class' => "dropdown-toggle",
                    'data-toggle' => "dropdown",
                    'role' => "button",
                    'aria-expanded' => "false"],
                'submenuOptions' => ['class' => "dropdown-menu", 'role' => "menu"]
            ),
        ),
        'htmlOptions' => ['class' => 'nav nav-tabs'],
    ));
    ?>



</div>
<?php if (Yii::app()->user->isGuest): ?>
    <?php if ($menu == false): ?>
        <h3 class="bg-warning">Меню на <?php echo date('d.m.Y', $date); ?> еще не сформированно</h3>
    <?php else: ?>
        <?php foreach ($menu as $category): ?>
            <h3><?php echo $category['name'] ?></h3>
            <table class="table">
                <colgroup>
                    <col width="5%"/>
                    <col width="75%"/>
                    <col width="10%"/>
                    <col width="10%"/>                
                </colgroup>
                <tr>
                    <th style="border-top:none;">#</th>
                    <th style="border-top:none;">Наименование</th>
                    <th style="border-top:none;">Вес</th>
                    <th style="border-top:none;">Цена</th>
                </tr>
                <?php $i = 0; ?>
                <?php foreach ($category['products'] as $row): ?>

                    <tr>
                        <td><?php echo ++$i ?></td>
                        <td><?= $row['name'] ?></td>
                        <td><?= $row['weight'] ?></td>
                        <td><?= $row['price'] ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endforeach; ?>
    <?php endif; ?>
<?php else: ?>
    <?php echo $this->renderPartial('_user_menu', ['menu' => $menu, 'date' => $date, 'dayofweek'=>$dayofweek]); ?>
<?php endif; ?>


protected/views/site/login.php
<div class="container">

    <form method="POST" action="" accept-charset="UTF-8">
        <div class="row">
            <legend>Введите электропочту и пароль</legend>            
            <div class="col-sm-3">
                <label>Почта</label>
                <input type="text" id="username" class="form-control" value="<?= !empty($_POST['username']) ? $_POST['username'] : '' ?>" name="username" placeholder="obeder@acquiropay.com">
            </div>
            <div class="col-sm-2">
                <label>Пароль:</label>
                <input type="password" id="password" class="form-control" value="<?= !empty($_POST['password']) ? $_POST['password'] : '' ?>" name="password" placeholder="Пароль">                    
            </div>
        </div>        
        <?php if (!empty($error)): ?>
            <div class="row">
                <div class="col-sm-4">
                    <p class="text-danger">Такая почта или пароль не существуют.</p>
                </div>
            </div>
        <?php endif; ?>        
        <div class="row col-sm-2">
            <p><?php echo CHtml::link('Забыл пароль', ['site/recovery']); ?> <?php echo CHtml::link('Регистрация', ['site/register']); ?></p>
            <button type="submit" name="submit" class="btn btn-info">Войти <span class="glyphicon glyphicon-triangle-right"></span></button>            

        </div>
    </form>
</div>


protected/views/site/order.php
<script src="<?php echo Yii::app()->getBaseUrl(); ?>/js/jquery-ui.min.js"></script>
<script>
    $(document).ready(function () {
        $.datepicker.regional['ru'] = {
            closeText: 'Закрыть',
            prevText: '&#x3c;Пред',
            nextText: 'След&#x3e;',
            currentText: 'Сегодня',
            monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
                'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
            monthNamesShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
                'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
            dayNames: ['воскресенье', 'понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота'],
            dayNamesShort: ['вск', 'пнд', 'втр', 'срд', 'чтв', 'птн', 'сбт'],
            dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            dateFormat: 'dd.mm.yy',
            firstDay: 1,
            isRTL: false,
        };
        $.datepicker.setDefaults($.datepicker.regional['ru']);
        $('#date').datepicker({onSelect: function (selectedDate) {

                window.location.href = '<?php echo Yii::app()->createUrl('site/order') ?>&date=' + $(this).val();
            }
        });
    });
</script>


<h3>Список заказов на <u><input id="date" value="<?php echo date('d.m.Y', $date); ?>" name="date" /></u></h3>
<?php if (empty($orders)): ?>
    <h3 class="bg-warning">Нет заказов на <?php echo date('d.m.Y', $date); ?></h3>
<?php else: ?>
    <?php foreach ($orders['users'] as $cur): ?>
        <h4><?php echo $cur['name']; ?></h4>

        <table class="table">
            <colgroup>
                <col width="5%"/>
                <col width="55%"/>
                <col width="10%"/>
                <col width="10%"/>
                <col width="10%"/>
                <col width="10%"/>
            </colgroup>
            <tr>
                <th>#</th>
                <th>Наименование</th>
                <th>Вес</th>
                <th>Цена</th>
                <th>Количество</th>
                <th>Итого</th>
                <td> </td>
            </tr>

            <?php
            $i = 0;
            ?>
            <?php foreach ($cur['products'] as $row): ?>
                <tr>
                    <td><?php echo ++$i ?></td>
                    <td><?= $row['name'] ?></td>
                    <td><?= $row['weight'] ?></td>
                    <td><?= $row['price'] ?></td>
                    <td><?= $row['count'] ?></td>
                    <td><?= $row['total'] ?></td>
                    <td><?php if($this->isAdmin()):?>
                        <div class="admin-remove"><?php echo CHtml::link('<span class="glyphicon glyphicon-remove"></span>', ['site/removeOrder', 'date'=>$date,'id'=>$row['order_id']], ['class'=>'btn btn-danger']);?></div>
                        <?php endif;?>
                    </td>
                </tr>

            <?php endforeach; ?>
            <tr>
                <td></td>
                <td></td>
                <td> </td>
                <td> </td>
                <td style="text-align: right">Сумма</td>
                <td><?php echo $cur['sum']; ?></td>
                <td> </td>

            </tr>
            <tr>
                <td></td>
                <td></td>
                <td> </td>
                <th colspan="2" style="text-align: right"> 
                    Сумма c доставкой</th>
                <th><?php echo $cur['total']; ?></th><td> </td>

            </tr>
        </table>
    <?php endforeach; ?>

    <h5>Доставка: <?php echo $orders['delivery']; ?> Руб.</h5>
    <h5>Сумма: <?php echo $orders['sum']; ?> Руб.</h5>
    <?php if($orders['sum'] < 1500):?>
    <h6>До бесплатной доставки не хватает <?php echo 1500-$orders['sum']; ?> Руб.</h6>
    <?php else:?>
    <h6>Бесплатная доставка</h6>
    <?php endif;?>
    <h4>Сумма с доставкой: <?php echo $orders['total']; ?> Руб.</h4>
    <?php if($this->isAdmin()):?>
    <form action="<?php echo Yii::app()->createUrl('site/download');?>" method="post">
        <input type="hidden" name="download" value="<?php echo $date; ?>" />
        <div class="admin-remove"><button type="submit" class="btn btn-primary">Скачать заказ <span class="glyphicon glyphicon-download"></span></button></div>
    </form>
    <?php endif; ?>
<?php endif; ?>

<p> </p>

protected/views/site/recovery.php
<div class="container">
    <?php if($sended):?>
    <h2>Ваш новый пароль выслан вам на почту</h2>
    <?php else: ?>
    <form method="POST" action="" accept-charset="UTF-8">
        <div class="row">
            <legend>Введите электропочту</legend>            
            <div class="col-sm-3">
                <label>Почта</label>
                <input type="text" id="username" class="form-control" value="<?= !empty($_POST['username']) ? $_POST['username'] : '' ?>" name="username" placeholder="obeder@acquiropay.com">
            </div>
        </div>        
        <?php if (!empty($error)): ?>
            <div class="row">
                <div class="col-sm-4">
                    <p class="text-danger">Такая почта не существует.</p>
                </div>
            </div>
        <?php endif; ?>        
        <div class="row col-sm-2">
            <p><?php echo CHtml::link('Регистрация', ['site/register']); ?></p>
            <button type="submit" name="submit" class="btn btn-info">Вспомнить</button>            

        </div>
    </form>
    <?php endif;?>
</div>

protected/views/site/register.php
<div class="container">

    <form method="POST" action="" accept-charset="UTF-8">
        <div class="row">
            <legend>Введите электропочту, пароль и имя</legend>            
            <div class="col-sm-3">
                <label>Имя</label>
                <input type="text" id="name" class="form-control" value="<?= !empty($_POST['name']) ? $_POST['name'] : '' ?>" name="name" placeholder="Джон">
            </div>
            
            <div class="col-sm-3">
                <label>Почта</label>
                <input type="text" id="username" class="form-control" value="<?= !empty($_POST['username']) ? $_POST['username'] : '' ?>" name="username" placeholder="obeder@acquiropay.com">
            </div>
            <div class="col-sm-2">
                <label>Пароль:</label>
                <input type="password" id="password" class="form-control" value="<?= !empty($_POST['password']) ? $_POST['password'] : '' ?>" name="password" placeholder="Пароль">                    
            </div>
        </div>        
        <?php if (!empty($error)): ?>
            <div class="row">
                <div class="col-sm-4">
                    <p class="text-danger">Такая почта существуют.</p>
                </div>
            </div>
        <?php endif; ?>        
        <div class="row col-sm-2">
            <p> </p>
            <button type="submit" name="submit" class="btn btn-info">Готово</button>            

        </div>
    </form>
</div>